import Welcome from "./welcome";

// ContentSection.jsx
export default function ContentSection({ active }) {
  return (
    <div className="mb-[150px] m-20 ">
      <Welcome/>
    <div className="flex justify-center items-center bg-slate-50 bg-opacity-20 rounded-3xl text-white text-center transition-all duration-700 px-4  max-w-400px">
      {active === "webdev" && <p className="p-10 w-300px ">I am a passionate Web Developer with hands-on experience in building responsive and interactive web applications. I specialize in HTML, CSS, JavaScript, React, and Tailwind CSS, creating visually appealing and user-friendly websites. My strong problem-solving skills and background in Java and Object-Oriented Programming (OOP) allow me to write clean, modular, and maintainable code. I enjoy transforming ideas into dynamic, pixel-perfect interfaces and have experience in integrating APIs, optimizing performance, and ensuring accessibility across devices. I strive to build web solutions that balance functionality, design, and user experience, continuously learning and adopting modern technologies to deliver impactful digital experiences.</p>}
      {active === "content" && <p className="p-10 w-300px">My journey as a Content Writer began in school, where I participated in composition competitions and was fortunate to win prizes. This early recognition became the motivation to pursue writing more seriously. During my college days, I achieved first prize in a district-level essay competition conducted by Nroot Academy, further strengthening my passion for creating impactful content. Today, I channel my creativity through my social media page @aloud_s_peaker, where I focus on content creation and writing, sharing engaging stories, informative posts, and thought-provoking ideas. Over the years, I have developed strong writing skills, attention to detail, and the ability to connect with audiences through clear and compelling narratives. I aim to continue growing as a writer while inspiring and engaging readers with every piece I create. ✍️</p>}
      {active === "designer" && <p className="p-10 w-300px">I am a passionate UI/UX Designer with experience in creating my own designs for website landing pages and social media posters. My interest in design grew from a desire to deliver user-friendly websites and seamless single-page applications (SPA) that provide engaging digital experiences. I also work as a freelancer, creating poster designs and managing content for my social media page @code_tech_2003. I am proficient with essential design tools such as Canva, Photoshop, and Figma, which I leverage to bring creative and visually appealing ideas to life. My focus is on blending aesthetic appeal with functionality, ensuring that each design not only looks great but also provides a smooth and intuitive user experience. 🎨</p>}
      {active === "tutor" && <p className="p-10 w-300px">I am a passionate Tutor who loves learning, which naturally inspires me to teach. I focus on sharing knowledge in digital marketing, coding, and emerging technologies through my channels, making complex concepts easier to understand. I have 3 months of teaching experience as a programming staff, where I enjoyed helping students grasp difficult topics. My teaching approach emphasizes simplifying concepts using real-life examples, ensuring learners can relate to and retain the material effectively. I take pride in fostering an engaging and supportive learning environment, encouraging curiosity and problem-solving skills among my students. 📚</p>}
    </div></div>
  );
}

